spring:
  jpa:
    show-sql: true
    generate-ddl: true
#  datasource:
#    username: ${rdb_username}
#    password: ${rdb_password}
rdb:
  username: "${rdb_username}"
  password: ${rdb_password}
  ws: ${rdb_wszystko}
